# Generated by Django 2.0.7 on 2018-07-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=50)),
                ('faculty_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('graduation_year', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('university_name', models.CharField(max_length=50)),
                ('vk_ID', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
