# Generated by Django 2.0.7 on 2018-07-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('class_begin_time', models.CharField(max_length=50)),
                ('class_end_time', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('class_serial_number', models.CharField(max_length=50)),
                ('class_type', models.CharField(max_length=50)),
                ('day_of_week', models.CharField(max_length=50)),
                ('room_name', models.CharField(max_length=50)),
                ('schedule_creation_time', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=50)),
                ('user_ID', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
